#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

"""
Tables in this file are coming from trace_parser_flags.cpp in ApiTrace
http://apitrace.github.io/

/**************************************************************************
 *
 * Copyright 2015 VMware, Inc.
 * Copyright 2011 Jose Fonseca
 * All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 **************************************************************************/
"""

class effectables:
    endOfFrame = ["glFrameTerminatorGREMEDY", "glFlush", "glFinish",
            "glClear", "IDXGIDecodeSwapChain::PresentBuffer",
            "IDXGISwapChain1::Present", "IDXGISwapChain1::Present1",
            "IDXGISwapChain2::Present", "IDXGISwapChain2::Present1",
            "IDXGISwapChain::Present", "IDXGISwapChainDWM::Present",
            "IDirect3DDevice8::Present", "IDirect3DDevice9::Present",
            "IDirect3DDevice9Ex::Present", "IDirect3DDevice9Ex::PresentEx",
            "IDirect3DSwapChain9::Present", "IDirect3DSwapChain9Ex::Present",
            "eglSwapBuffers", "glXSwapBuffers", "wglSwapBuffers",
            "wglSwapLayerBuffers", "wglSwapMultipleBuffers"]
    noEffect = [
            "CGLGetCurrentContext", "D3DPERF_BeginEvent", "D3DPERF_EndEvent",
            "D3DPERF_SetMarker", "ID3D10Device1::CheckMultisampleQualityLevels",
            "ID3D10Device::CheckMultisampleQualityLevels",
            "ID3D11Device::CheckMultisampleQualityLevels",
            "ID3DUserDefinedAnnotation::BeginEvent",
            "ID3DUserDefinedAnnotation::EndEvent",
            "ID3DUserDefinedAnnotation::SetMarker",
            "IDirect3D8::CheckDeviceFormat", "IDirect3D8::EnumAdapterModes",
            "IDirect3D8::GetAdapterModeCount", "IDirect3D8::GetDeviceCaps",
            "IDirect3D9::CheckDeviceFormat", "IDirect3D9::EnumAdapterModes",
            "IDirect3D9::GetAdapterModeCount", "IDirect3D9::GetDeviceCaps",
            "IDirect3D9Ex::CheckDeviceFormat", "IDirect3D9Ex::EnumAdapterModes",
            "IDirect3D9Ex::GetAdapterModeCount", "IDirect3D9Ex::GetDeviceCaps",
            "IDirect3DDevice8::GetDeviceCaps", "IDirect3DDevice9::GetDeviceCaps",
            "IDirect3DDevice9Ex::GetDeviceCaps", "eglGetProcAddress",
            "eglQueryString", "glAreProgramsResidentNV", "glAreTexturesResident",
            "glAreTexturesResidentEXT", "glBufferRegionEnabled",
            "glDebugMessageControl", "glDebugMessageControlARB",
            "glDebugMessageEnableAMD", "glDebugMessageInsert",
            "glDebugMessageInsertAMD", "glDebugMessageInsertARB",
            "glDebugMessageInsertKHR", "glGetActiveAtomicCounterBufferiv",
            "glGetActiveAttrib", "glGetActiveAttribARB",
            "glGetActiveSubroutineName", "glGetActiveSubroutineUniformName",
            "glGetActiveSubroutineUniformiv", "glGetActiveUniform",
            "glGetActiveUniformARB", "glGetActiveUniformBlockName",
            "glGetActiveUniformBlockiv", "glGetActiveUniformName",
            "glGetActiveUniformsiv", "glGetActiveVaryingNV",
            "glGetArrayObjectfvATI", "glGetArrayObjectivATI",
            "glGetAttachedObjectsARB", "glGetAttachedShaders",
            "glGetBooleanIndexedvEXT", "glGetBooleani_v", "glGetBooleanv",
            "glGetBufferParameteri64v", "glGetBufferParameteriv",
            "glGetBufferParameterivARB", "glGetBufferParameterui64vNV",
            "glGetBufferPointerv", "glGetBufferPointervARB", "glGetBufferSubData",
            "glGetBufferSubDataARB", "glGetClipPlane", "glGetColorTable",
            "glGetColorTableEXT", "glGetColorTableParameterfv",
            "glGetColorTableParameterfvEXT", "glGetColorTableParameterfvSGI",
            "glGetColorTableParameteriv", "glGetColorTableParameterivEXT",
            "glGetColorTableParameterivSGI", "glGetColorTableSGI",
            "glGetCombinerInputParameterfvNV", "glGetCombinerInputParameterivNV",
            "glGetCombinerOutputParameterfvNV", "glGetCombinerOutputParameterivNV",
            "glGetCombinerStageParameterfvNV", "glGetConvolutionFilterEXT",
            "glGetConvolutionParameterfv", "glGetConvolutionParameterfvEXT",
            "glGetConvolutionParameteriv", "glGetConvolutionParameterivEXT",
            "glGetDetailTexFuncSGIS", "glGetDoubleIndexedvEXT", "glGetDoublei_v",
            "glGetDoublev", "glGetError", "glGetFenceivNV",
            "glGetFinalCombinerInputParameterfvNV",
            "glGetFinalCombinerInputParameterivNV", "glGetFloatIndexedvEXT",
            "glGetFloati_v", "glGetFloatv", "glGetFogFuncSGIS",
            "glGetFragDataIndex", "glGetFragmentLightfvSGIX",
            "glGetFragmentLightivSGIX", "glGetFragmentMaterialfvSGIX",
            "glGetFragmentMaterialivSGIX", "glGetFramebufferAttachmentParameteriv",
            "glGetFramebufferAttachmentParameterivEXT",
            "glGetFramebufferParameteriv", "glGetFramebufferParameterivEXT",
            "glGetGraphicsResetStatusARB", "glGetHandleARB", "glGetHistogramEXT",
            "glGetHistogramParameterfv", "glGetHistogramParameterfvEXT",
            "glGetHistogramParameteriv", "glGetHistogramParameterivEXT",
            "glGetImageTransformParameterfvHP", "glGetImageTransformParameterivHP",
            "glGetInfoLogARB", "glGetInstrumentsSGIX", "glGetInteger64i_v",
            "glGetInteger64v", "glGetIntegerIndexedvEXT", "glGetIntegeri_v",
            "glGetIntegerui64i_vNV", "glGetIntegerui64vNV", "glGetIntegerv",
            "glGetInternalformati64v", "glGetInternalformativ",
            "glGetInvariantBooleanvEXT", "glGetInvariantFloatvEXT",
            "glGetInvariantIntegervEXT", "glGetLightfv", "glGetLightiv",
            "glGetListParameterfvSGIX", "glGetListParameterivSGIX",
            "glGetLocalConstantBooleanvEXT", "glGetLocalConstantFloatvEXT",
            "glGetLocalConstantIntegervEXT", "glGetMapAttribParameterfvNV",
            "glGetMapAttribParameterivNV", "glGetMapControlPointsNV",
            "glGetMapParameterfvNV", "glGetMapParameterivNV", "glGetMapdv",
            "glGetMapfv", "glGetMapiv", "glGetMaterialfv", "glGetMaterialiv",
            "glGetMinmaxEXT", "glGetMinmaxParameterfv",
            "glGetMinmaxParameterfvEXT", "glGetMinmaxParameteriv",
            "glGetMinmaxParameterivEXT", "glGetMultiTexEnvfvEXT",
            "glGetMultiTexEnvivEXT", "glGetMultiTexGendvEXT",
            "glGetMultiTexGenfvEXT", "glGetMultiTexGenivEXT",
            "glGetMultiTexLevelParameterfvEXT", "glGetMultiTexLevelParameterivEXT",
            "glGetMultiTexParameterIivEXT", "glGetMultiTexParameterIuivEXT",
            "glGetMultiTexParameterfvEXT", "glGetMultiTexParameterivEXT",
            "glGetMultisamplefv", "glGetMultisamplefvNV",
            "glGetNamedBufferParameterivEXT", "glGetNamedBufferParameterui64vNV",
            "glGetNamedBufferPointervEXT", "glGetNamedBufferSubDataEXT",
            "glGetNamedFramebufferAttachmentParameterivEXT",
            "glGetNamedFramebufferParameterivEXT",
            "glGetNamedProgramLocalParameterIivEXT",
            "glGetNamedProgramLocalParameterIuivEXT",
            "glGetNamedProgramLocalParameterdvEXT",
            "glGetNamedProgramLocalParameterfvEXT", "glGetNamedProgramStringEXT",
            "glGetNamedProgramivEXT", "glGetNamedRenderbufferParameterivEXT",
            "glGetNamedStringARB", "glGetNamedStringivARB",
            "glGetObjectBufferfvATI", "glGetObjectBufferivATI", "glGetObjectLabel",
            "glGetObjectParameterfvARB", "glGetObjectParameterivAPPLE",
            "glGetObjectParameterivARB", "glGetObjectPtrLabel",
            "glGetOcclusionQueryivNV", "glGetOcclusionQueryuivNV",
            "glGetPerfMonitorCounterDataAMD", "glGetPerfMonitorCounterInfoAMD",
            "glGetPerfMonitorCounterStringAMD", "glGetPerfMonitorCountersAMD",
            "glGetPerfMonitorGroupStringAMD", "glGetPerfMonitorGroupsAMD",
            "glGetPixelTexGenParameterfvSGIS", "glGetPixelTexGenParameterivSGIS",
            "glGetPointerIndexedvEXT", "glGetPointerv", "glGetPointervEXT",
            "glGetProgramBinary", "glGetProgramEnvParameterIivNV",
            "glGetProgramEnvParameterIuivNV", "glGetProgramEnvParameterdvARB",
            "glGetProgramEnvParameterfvARB", "glGetProgramInfoLog",
            "glGetProgramInterfaceiv", "glGetProgramLocalParameterIivNV",
            "glGetProgramLocalParameterIuivNV", "glGetProgramLocalParameterdvARB",
            "glGetProgramLocalParameterfvARB", "glGetProgramNamedParameterdvNV",
            "glGetProgramNamedParameterfvNV", "glGetProgramParameterdvNV",
            "glGetProgramParameterfvNV", "glGetProgramPipelineInfoLog",
            "glGetProgramPipelineiv", "glGetProgramResourceIndex",
            "glGetProgramResourceLocation", "glGetProgramResourceLocationIndex",
            "glGetProgramResourceName", "glGetProgramResourceiv",
            "glGetProgramStageiv", "glGetProgramStringARB", "glGetProgramStringNV",
            "glGetProgramSubroutineParameteruivNV", "glGetProgramiv",
            "glGetProgramivARB", "glGetProgramivNV", "glGetQueryIndexediv",
            "glGetQueryObjecti64v","glGetQueryObjecti64vEXT", "glGetQueryObjectiv",
            "glGetQueryObjectivARB", "glGetQueryObjectui64v",
            "glGetQueryObjectui64vEXT", "glGetQueryObjectuiv",
            "glGetQueryObjectuivARB", "glGetQueryiv", "glGetQueryivARB",
            "glGetRenderbufferParameteriv", "glGetRenderbufferParameterivEXT",
            "glGetSamplerParameterIiv", "glGetSamplerParameterIuiv",
            "glGetSamplerParameterfv", "glGetSamplerParameteriv",
            "glGetSeparableFilterEXT", "glGetShaderInfoLog",
            "glGetShaderPrecisionFormat", "glGetShaderSource",
            "glGetShaderSourceARB", "glGetShaderiv", "glGetSharpenTexFuncSGIS",
            "glGetString", "glGetStringi", "glGetSynciv",
            "glGetTexBumpParameterfvATI", "glGetTexBumpParameterivATI",
            "glGetTexEnvfv", "glGetTexEnviv", "glGetTexFilterFuncSGIS",
            "glGetTexGendv", "glGetTexGenfv", "glGetTexGeniv",
            "glGetTexLevelParameterfv", "glGetTexLevelParameteriv",
            "glGetTexParameterIiv", "glGetTexParameterIivEXT",
            "glGetTexParameterIuiv", "glGetTexParameterIuivEXT",
            "glGetTexParameterPointervAPPLE", "glGetTexParameterfv",
            "glGetTexParameteriv", "glGetTextureLevelParameterfvEXT",
            "glGetTextureLevelParameterivEXT", "glGetTextureParameterIivEXT",
            "glGetTextureParameterIuivEXT", "glGetTextureParameterfvEXT",
            "glGetTextureParameterivEXT", "glGetTrackMatrixivNV",
            "glGetTransformFeedbackVarying", "glGetTransformFeedbackVaryingEXT",
            "glGetTransformFeedbackVaryingNV", "glGetUniformIndices",
            "glGetUniformSubroutineuiv", "glGetUniformdv", "glGetUniformfv",
            "glGetUniformfvARB", "glGetUniformi64vNV", "glGetUniformiv",
            "glGetUniformivARB", "glGetUniformui64vNV", "glGetUniformuiv",
            "glGetUniformuivEXT", "glGetVariantArrayObjectfvATI",
            "glGetVariantArrayObjectivATI", "glGetVariantBooleanvEXT",
            "glGetVariantFloatvEXT", "glGetVariantIntegervEXT",
            "glGetVariantPointervEXT", "glGetVertexArrayIntegeri_vEXT",
            "glGetVertexArrayIntegervEXT", "glGetVertexArrayPointeri_vEXT",
            "glGetVertexArrayPointervEXT", "glGetVertexAttribArrayObjectfvATI",
            "glGetVertexAttribArrayObjectivATI", "glGetVertexAttribIiv",
            "glGetVertexAttribIivEXT", "glGetVertexAttribIuiv",
            "glGetVertexAttribIuivEXT", "glGetVertexAttribLdv",
            "glGetVertexAttribLdvEXT", "glGetVertexAttribLi64vNV",
            "glGetVertexAttribLui64vNV", "glGetVertexAttribPointerv",
            "glGetVertexAttribPointervARB", "glGetVertexAttribPointervNV",
            "glGetVertexAttribdv", "glGetVertexAttribdvARB",
            "glGetVertexAttribdvNV", "glGetVertexAttribfv",
            "glGetVertexAttribfvARB", "glGetVertexAttribfvNV",
            "glGetVertexAttribiv", "glGetVertexAttribivARB",
            "glGetVertexAttribivNV", "glGetVideoCaptureStreamdvNV",
            "glGetVideoCaptureStreamfvNV", "glGetVideoCaptureStreamivNV",
            "glGetVideoCaptureivNV", "glGetVideoi64vNV", "glGetVideoivNV",
            "glGetVideoui64vNV", "glGetVideouivNV", "glGetnMapdvARB",
            "glGetnMapfvARB", "glGetnMapivARB", "glGetnUniformdvARB",
            "glGetnUniformfvARB", "glGetnUniformivARB", "glGetnUniformuivARB",
            "glInsertEventMarkerEXT", "glIsAsyncMarkerSGIX", "glIsBuffer",
            "glIsBufferARB", "glIsBufferResidentNV", "glIsEnabled",
            "glIsEnabledIndexedEXT", "glIsEnabledi", "glIsFenceAPPLE",
            "glIsFenceNV", "glIsFramebuffer", "glIsFramebufferEXT", "glIsList",
            "glIsNameAMD", "glIsNamedBufferResidentNV", "glIsNamedStringARB",
            "glIsObjectBufferATI", "glIsOcclusionQueryNV", "glIsProgram",
            "glIsProgramARB", "glIsProgramNV", "glIsProgramPipeline", "glIsQuery",
            "glIsQueryARB", "glIsRenderbuffer", "glIsRenderbufferEXT",
            "glIsSampler", "glIsShader", "glIsSync", "glIsTexture",
            "glIsTextureEXT", "glIsTransformFeedback", "glIsTransformFeedbackNV",
            "glIsVariantEnabledEXT", "glIsVertexArray", "glIsVertexArrayAPPLE",
            "glIsVertexAttribEnabledAPPLE", "glObjectLabel", "glObjectLabelKHR",
            "glObjectPtrLabel", "glObjectPtrLabelKHR", "glPopDebugGroup",
            "glPopDebugGroupKHR", "glPopGroupMarkerEXT", "glPushDebugGroup",
            "glPushDebugGroupKHR", "glPushGroupMarkerEXT", "glStringMarkerGREMEDY",
            "glXGetClientString", "glXGetConfig", "glXGetCurrentContext",
            "glXGetCurrentDisplay", "glXGetCurrentDisplayEXT",
            "glXGetCurrentDrawable", "glXGetCurrentReadDrawable",
            "glXGetCurrentReadDrawableSGI", "glXGetProcAddress",
            "glXGetProcAddressARB", "glXIsDirect", "glXQueryExtension",
            "glXQueryExtensionsString", "glXQueryVersion","wglDescribePixelFormat",
            "wglGetCurrentContext", "wglGetCurrentDC", "wglGetDefaultProcAddress",
            "wglGetExtensionsStringARB", "wglGetExtensionsStringEXT",
            "wglGetPixelFormat","wglGetProcAddress"]
